gui:
  theme:
    activeBorderColor:
      - '#7AA2F7'
      - bold
    inactiveBorderColor:
      - '#3B4261'
    optionsTextColor:
      - '#9ECE6A'
    selectedLineBgColor:
      - '#1F2335'
    cherryPickedCommitBgColor:
      - '#2E3440'
    cherryPickedCommitFgColor:
      - '#7AA2F7'
    unstagedChangesColor:
      - '#F7768E'
    defaultFgColor:
      - '#C0CAF5'
    searchingActiveBorderColor:
      - '#E0AF68'

  authorColors:
    '*': '#BB9AF7'
