[mgr]
cwd = { fg = "#81c8be" }

hovered         = { fg = "#303446", bg = "#8caaee" }
preview_hovered = { fg = "#c6d0f5", bg = "#626880" }

find_keyword  = { fg = "#e5c890", italic = true }
find_position = { fg = "#ca9ee6", bg = "reset", italic = true }

marker_copied   = { fg = "#99d1db", bg = "#99d1db" }
marker_cut      = { fg = "#e78284", bg = "#e78284" }
marker_marked   = { fg = "#8caaee", bg = "#8caaee" }
marker_selected = { fg = "#81c8be", bg = "#81c8be" }

count_copied   = { fg = "#303446", bg = "#99d1db" }
count_cut      = { fg = "#303446", bg = "#e78284" }
count_selected = { fg = "#303446", bg = "#8caaee" }

border_symbol = "│"
border_style  = { fg = "#626880" }

[tabs]
active   = { fg = "#303446", bg = "#f2d5cf", bold = true }
inactive = { fg = "#f2d5cf", bg = "#626880" }

[mode]
normal_main = { fg = "#303446", bg = "#8caaee", bold = true }
normal_alt  = { fg = "#8caaee", bg = "#292c3c"}

select_main = { fg = "#303446", bg = "#99d1db", bold = true }
select_alt  = { fg = "#99d1db", bg = "#292c3c"}

unset_main  = { fg = "#303446", bg = "#ef9f76", bold = true }
unset_alt   = { fg = "#ef9f76", bg = "#292c3c"}

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8caaee", bg = "#626880" }
progress_error  = { fg = "#e78284", bg = "#626880" }

perm_type  = { fg = "#8caaee" }
perm_read  = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec  = { fg = "#99d1db" }
perm_sep   = { fg = "#626880" }

[input]
border   = { fg = "#8caaee" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#8caaee" }
active   = { fg = "#ca9ee6" }
inactive = {}

[confirm]
border     = { fg = "#8caaee" }
title      = { fg = "#8caaee" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#8caaee" }

[tasks]
border  = { fg = "#8caaee" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#292c3c" }
cand            = { fg = "#99d1db" }
rest            = { fg = "#c6d0f5" }
desc            = { fg = "#ca9ee6" }
separator       = "  "
separator_style = { fg = "#626880" }

[help]
on      = { fg = "#99d1db" }
run     = { fg = "#ca9ee6" }
desc    = { fg = "#c6d0f5" }
hovered = { bg = "#626880", bold = true }
footer  = { fg = "#f2d5cf", bg = "#626880" }

[notify]
title_info  = { fg = "#99d1db" }
title_warn  = { fg = "#e5c890" }
title_error = { fg = "#e78284" }

[filetype]
rules = [
	{ mime = "image/*", fg = "#99d1db" },
	{ mime = "{audio,video}/*", fg = "#e5c890" },
	{ mime = "application/*zip", fg = "#ca9ee6" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ca9ee6" },
	{ mime = "application/{pdf,doc,rtf}", fg = "#99d1db" },
	{ name = "*", fg = "#f2d5cf" },
	{ name = "*/", fg = "#8caaee" }
]

[spot]
border   = { fg = "#8caaee" }
title    = { fg = "#8caaee" }
tbl_cell = { fg = "#8caaee", reversed = true }
tbl_col  = { bold = true }

[icon]
dirs = [
  { name = ".git", text = "󰝰", fg = "#8caaee" },
  { name = ".config", text = "󱁿", fg = "#8caaee" },
  { name = "Descargas", text = "󰉍", fg = "#8caaee" },
  { name = "Documentos", text = "󱧶", fg = "#8caaee" },
  { name = "Imágenes", text = "󰉏", fg = "#8caaee" },
  { name = "Música", text = "󱍙", fg = "#8caaee" },
  { name = "Vídeos", text =  "󱧺", fg = "#8caaee" }
]

files = [
  { name = "README.md", text = "󰍔", fg = "#c6d0f5" },
  { name = "hyprland.conf", text = "", fg = "#c6d0f5" },
  { name = ".gitignore", text = "󰊢", fg = "#c6d0f5" },
  { name = "config", text = "󱁻", fg = "#c6d0f5" } 
]

exts = [
  { name = "nix", text = "󱄅", fg = "#c6d0f5" },
  { name = "ini", text = "󱁻", fg = "#c6d0f5" },
  { name = "toml", text = "", fg = "#c6d0f5" },
  { name = "conf", text = "󱁻", fg = "#c6d0f5" },
  { name = "svg", text = "󰜡", fg = "#c6d0f5" },
  { name = "json", text = "󰘦", fg = "#c6d0f5" },
  { name = "py", text = "󰌠", fg = "#c6d0f5" },
  { name = "srt", text = "󰨖", fg = "#c6d0f5" },
  { name = "lock", text = "󰈡", fg = "#c6d0f5" },
  { name = "txt", text = "󰈙", fg = "#c6d0f5" },
  { name = "lua", text = "󰢱", fg = "#c6d0f5" }
]

conds = [
  { if = "!dir & link", text = "󱅷", fg = "#c6d0f5" },
  { if = "!file & link", text =  "󰌷", fg = "#8caaee" },
  { if = "!(dir | link)", text = "󰈔", fg = "#c6d0f5" },
  { if = "dir", text = "󰝰", fg = "#8caaee" },
]
