[mgr]
cwd = { fg = "#88c0d0" }

hovered         = { fg = "#2e3440", bg = "#81a1c1" }
preview_hovered = { fg = "#d8dee9", bg = "#4c566a" }

find_keyword  = { fg = "#ebcb8b", italic = true }
find_position = { fg = "#b48ead", bg = "reset", italic = true }

marker_copied   = { fg = "#a3be8c", bg = "#a3be8c" }
marker_cut      = { fg = "#bf616a", bg = "#bf616a" }
marker_marked   = { fg = "#5e81ac", bg = "#5e81ac" }
marker_selected = { fg = "#88c0d0", bg = "#81a1c1" }

count_copied   = { fg = "#2e3440", bg = "#a3be8c" }
count_cut      = { fg = "#2e3440", bg = "#bf616a" }
count_selected = { fg = "#2e3440", bg = "#81a1c1" }

border_symbol = "│"
border_style  = { fg = "#4c566a" }

# syntect_theme = "~/.config/yazi/Nord.tmTheme"

[tabs]
active   = { fg = "#2e3440", bg = "#eceff4", bold = true }
inactive = { fg = "#eceff4", bg = "#4c566a" }

[mode]
normal_main = { fg = "#2e3440", bg = "#81a1c1", bold = true }
normal_alt  = { fg = "#88c0d0", bg = "#3b4252"}

select_main = { fg = "#2e3440", bg = "#a3be8c", bold = true }
select_alt  = { fg = "#a3be8c", bg = "#3b4252"}

unset_main  = { fg = "#2e3440", bg = "#d08770", bold = true }
unset_alt   = { fg = "#d08770", bg = "#3b4252"}

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#88c0d0", bg = "#4c566a" }
progress_error  = { fg = "#bf616a", bg = "#4c566a" }

perm_type  = { fg = "#81a1c1" }
perm_read  = { fg = "#ebcb8b" }
perm_write = { fg = "#bf616a" }
perm_exec  = { fg = "#a3be8c" }
perm_sep   = { fg = "#4c566a" }

[input]
border   = { fg = "#81a1c1" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#81a1c1" }
active   = { fg = "#b48ead" }
inactive = {}

[confirm]
border     = { fg = "#81a1c1" }
title      = { fg = "#81a1c1" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#81a1c1" }

[tasks]
border  = { fg = "#81a1c1" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#3b4252" }
cand            = { fg = "#8fbcbb" }
rest            = { fg = "#d8dee9" }
desc            = { fg = "#b48ead" }
separator       = "  "
separator_style = { fg = "#4c566a" }

[help]
on      = { fg = "#8fbcbb" }
run     = { fg = "#b48ead" }
desc    = { fg = "#d8dee9" }
hovered = { bg = "#4c566a", bold = true }
footer  = { fg = "#eceff4", bg = "#4c566a" }

[notify]
title_info  = { fg = "#8fbcbb" }
title_warn  = { fg = "#ebcb8b" }
title_error = { fg = "#bf616a" }

[filetype]
rules = [
	{ mime = "image/*", fg = "#8fbcbb" },
	{ mime = "{audio,video}/*", fg = "#ebcb8b" },
	{ mime = "application/*zip", fg = "#b48ead" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#b48ead" },
	{ mime = "application/{pdf,doc,rtf}", fg = "#a3be8c" },
	{ name = "*", fg = "#eceff4" },
	{ name = "*/", fg = "#81a1c1" }
]

[spot]
border   = { fg = "#81a1c1" }
title    = { fg = "#81a1c1" }
tbl_cell = { fg = "#81a1c1", reversed = true }
tbl_col  = { bold = true }

[icon]
dirs = [
  { name = ".git", text = "", fg = "#81a1c1" },
  { name = "Escritorio", text = "", fg = "#81a1c1" },
  { name = "Descargas", text = "", fg = "#81a1c1" },
  { name = "Documentos", text = "", fg = "#81a1c1" },
  { name = "Imágenes", text = "", fg = "#81a1c1" },
  { name = "Música", text = "", fg = "#81a1c1" },
  { name = "Vídeos", text =  "", fg = "#81a1c1" }
]

files = [
  { name = "README.md", text = "", fg = "#d8dee9" },
  { name = "hyprland.conf", text = "", fg = "#d8dee9" },
  { name = ".gitignore", text = "", fg = "#d8dee9" },
  { name = "config", text = "", fg = "#d8dee9" } 
]

exts = [
  { name = "nix", text = "", fg = "#d8dee9" },
  { name = "ini", text = "", fg = "#d8dee9" },
  { name = "toml", text = "", fg = "#d8dee9" },
  { name = "conf", text = "", fg = "#d8dee9" },
  { name = "svg", text = "", fg = "#d8dee9" },
  { name = "json", text = "", fg = "#d8dee9" },
  { name = "py", text = "󰌠", fg = "#d8dee9" },
  { name = "lock", text = "", fg = "#d8dee9" },
  { name = "lua", text = "", fg = "#d8dee9" }
]

conds = [
  { if = "!dir & link", text = "", fg = "#d8dee9" },
  { if = "!file & link", text =  "", fg = "#81a1c1" },
  { if = "!(dir | link)", text = "", fg = "#d8dee9" },
  { if = "dir", text = "", fg = "#81a1c1" },
]
